lagunage: node_js
node_js:
  - 7.9.0
sudo: required

cache:
  directories:
    - node_modules

before_install:
  - export SOURCE=`pwd`/
  - export GENERATE_DIR=`pwd`/../blog-generage/
  - mkdir -p $GENERATE_DIR
install:
  - npm install -g hexo-cli
  - npm install -g hexo-generator-sitemap
  - npm install -g hexo-generator-baidu-sitemap

before_script:
    - hexo init $GENERATE_DIR/
    - rm -r $GENERATE_DIR/source
    - cp -r ./* $GENERATE_DIR
    - cd $GENERATE_DIR

script:
    - git clone https://github.com/theme-next/hexo-theme-next themes/next
    - cp $SOURCE/theme_config.yml themes/next/_config.yml
    - hexo g
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: master
  local-dir: ../blog-generage/public/
  on:
    branch: master

  repo: raomuyang/raomuyang.github.io
