lagunage: node_js
node_js:
  - 7.9.0
sudo: required

cache:
  directories:
    - node_modules

before_install:
  - export SOURCE=`pwd`/
  - export GENERATE_DIR=`pwd`/../blog-generage/
  - mkdir -p $GENERATE_DIR
install:
    - make env
script:
    - make compile
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: master
  local-dir: ../blog-generate/public/
  on:
    branch: CICD 

  repo: raomuyang/raomuyang.github.io
